historical_air_pollution:
  outputs:
    prod:
      dataset: prod
      fixed_retries: 1
      keyfile: /home/src/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: <gcp-project-id>
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: prod